# Generated by Django 5.1.6 on 2025-02-11 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebateSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "topic",
                    models.CharField(
                        help_text="Title or topic of the debate session", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the debate session",
                        null=True,
                    ),
                ),
                ("start_time", models.DateTimeField(help_text="Debate start time")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, help_text="Debate end time", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the debate session is active",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        help_text="Moderator of the debate session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_debates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Argument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField(help_text="Content of the argument")),
                (
                    "vote_count",
                    models.IntegerField(
                        default=0, help_text="Net vote count for the argument"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who posted the argument",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arguments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent argument for threaded discussions",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="debate_arena.argument",
                    ),
                ),
                (
                    "debate_session",
                    models.ForeignKey(
                        help_text="Debate session this argument belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arguments",
                        to="debate_arena.debatesession",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VoteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vote_value",
                    models.IntegerField(help_text="Vote value, e.g., +1 or -1"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the vote was cast"
                    ),
                ),
                (
                    "argument",
                    models.ForeignKey(
                        help_text="The argument being voted on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_records",
                        to="debate_arena.argument",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        help_text="User who cast the vote",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
