# Generated by Django 5.1.6 on 2025-02-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the knowledge unit.", max_length=255
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Rich text content of the knowledge unit."
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True,
                        help_text="JSON list of attachment URLs or metadata.",
                        null=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="Language code for the content.",
                        max_length=10,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number of the knowledge unit."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
