# Generated by Django 5.1.6 on 2025-02-11 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebateTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the debate topic", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the debate topic"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the debate topic is active"
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True, help_text="Publish date of the topic", null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeaturedDebate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for display"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Whether this featured entry is active"
                    ),
                ),
                (
                    "debate_topic",
                    models.ForeignKey(
                        help_text="Featured debate topic",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_entries",
                        to="home.debatetopic",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonalizedRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.FloatField(
                        default=0, help_text="Relevance score for the recommendation"
                    ),
                ),
                (
                    "debate_topic",
                    models.ForeignKey(
                        help_text="Recommended debate topic",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="home.debatetopic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User receiving the recommendation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
