# Generated by Django 5.1.6 on 2025-02-11 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GapAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "planned_progress",
                    models.PositiveIntegerField(
                        help_text="Planned progress percentage."
                    ),
                ),
                (
                    "actual_progress",
                    models.PositiveIntegerField(
                        help_text="Actual progress percentage."
                    ),
                ),
                (
                    "gap",
                    models.PositiveIntegerField(
                        help_text="Difference between planned and actual progress."
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        help_text="Recommendations to close the gap.",
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project for which the gap analysis is performed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gap_analyses",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
