# Generated by Django 5.1.6 on 2025-02-11 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the document.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the document.", null=True
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        help_text="Uploaded document file.",
                        upload_to="knowledge_documents/",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", help_text="Document version.", max_length=50
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created/uploaded the document.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revision_number",
                    models.CharField(
                        help_text="Revision number or identifier.", max_length=50
                    ),
                ),
                (
                    "changes",
                    models.TextField(
                        help_text="Description of the changes in this revision."
                    ),
                ),
                (
                    "revised_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the revision was made.",
                    ),
                ),
                (
                    "revised_by",
                    models.ForeignKey(
                        help_text="User who made the revision.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "knowledge_document",
                    models.ForeignKey(
                        help_text="The document to which this revision belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="knowledge_hub.knowledgedocument",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
