# Generated by Django 5.1.6 on 2025-02-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DebateArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the archived debate or text", max_length=255
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full text content for search and analysis"
                    ),
                ),
                (
                    "debate_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of the debate or publication",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source or reference of the material",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        help_text="List of tags for filtering and search",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
