# Generated by Django 5.1.6 on 2025-02-11 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("debate_arena", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebateResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_text",
                    models.TextField(
                        help_text="Final resolution details and decisions"
                    ),
                ),
                (
                    "decision_history",
                    models.JSONField(
                        blank=True,
                        help_text="JSON record of decision history and audit trail",
                        null=True,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the resolution was approved",
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved the resolution",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "debate_session",
                    models.OneToOneField(
                        help_text="Debate session for which this resolution applies",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolution",
                        to="debate_arena.debatesession",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
