# Generated by Django 5.1.6 on 2025-02-11 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collab_spaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                help_text="User who sent the message.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collabspace",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created the space.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collab_spaces_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collabspace",
            name="participants",
            field=models.ManyToManyField(
                help_text="Users participating in the space.",
                related_name="collab_spaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="collab_space",
            field=models.ForeignKey(
                help_text="Collaboration space where the message was sent.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="collab_spaces.collabspace",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="collab_space",
            field=models.ForeignKey(
                help_text="Collaboration space where the document is shared.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="collab_spaces.collabspace",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="User who uploaded the document.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
