# Generated by Django 5.1.6 on 2025-02-11 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exhibition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the exhibition", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the exhibition", null=True
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Exhibition start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Exhibition end date", null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location of the exhibition",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(help_text="Title of the artwork", max_length=255),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the artwork"),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image of the artwork", upload_to="artworks/"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata (e.g., dimensions, medium)",
                        null=True,
                    ),
                ),
                (
                    "exhibition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Exhibition where the artwork is displayed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artworks",
                        to="artworks.exhibition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
