# Generated by Django 5.1.6 on 2025-02-11 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("foundation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("text", models.TextField(help_text="The question text.")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("multiple_choice", "Multiple Choice"),
                        ],
                        default="text",
                        help_text="Type of question.",
                        max_length=20,
                    ),
                ),
                (
                    "correct_answer",
                    models.TextField(
                        blank=True,
                        help_text="Correct answer for the question (if applicable).",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(help_text="Title of the lesson.", max_length=255),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Lesson content, which may include rich text, images, and video links."
                    ),
                ),
                (
                    "knowledge_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated knowledge unit, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="foundation.knowledgeunit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("text", models.TextField(help_text="Answer option text.")),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this is the correct answer.",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="The question this answer belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="learning.question",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(help_text="Title of the quiz.", max_length=255),
                ),
                (
                    "instructions",
                    models.TextField(help_text="Quiz instructions or guidelines."),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time limit in minutes, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="Lesson associated with this quiz.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="learning.lesson",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                help_text="Quiz to which this question belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="learning.quiz",
            ),
        ),
    ]
