# Generated by Django 5.1.6 on 2025-02-11 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("debate_arena", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebateEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        help_text="Type of event (e.g., 'argument_posted', 'vote_cast')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the event",
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of the event"
                    ),
                ),
                (
                    "debate_session",
                    models.ForeignKey(
                        help_text="Debate session associated with this event",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_logs",
                        to="debate_arena.debatesession",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DebateStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "metric_name",
                    models.CharField(
                        help_text="Name of the metric (e.g., total_votes, active_participants)",
                        max_length=100,
                    ),
                ),
                ("value", models.FloatField(help_text="Recorded value of the metric")),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the metric was recorded",
                    ),
                ),
                (
                    "debate_session",
                    models.ForeignKey(
                        help_text="Associated debate session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="debate_arena.debatesession",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
