# Generated by Django 5.1.6 on 2025-02-11 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscussionThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the discussion thread.", max_length=255
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Initial content or description of the thread."
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who started the discussion.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussion_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField(help_text="Content of the comment.")),
                (
                    "vote_count",
                    models.IntegerField(
                        default=0, help_text="Net vote count for the comment."
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who posted the comment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent comment if this is a reply; null if top-level.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="konnectedcommunity.comment",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        help_text="The discussion thread to which this comment belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="konnectedcommunity.discussionthread",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
