# Generated by Django 5.1.6 on 2025-02-11 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamFormationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "required_roles",
                    models.JSONField(
                        blank=True,
                        help_text="JSON specifying required roles and skills.",
                        null=True,
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True,
                        help_text="Additional information about the request.",
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project for which the team is being formed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_formation_requests",
                        to="projects.project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="User who initiated the team formation request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_formation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeamFormationCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        help_text="JSON data representing the user's skills.",
                        null=True,
                    ),
                ),
                (
                    "compatibility_score",
                    models.FloatField(
                        default=0, help_text="Computed compatibility score."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User being considered for the team.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_formation_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "formation_request",
                    models.ForeignKey(
                        help_text="Associated team formation request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="team_formation.teamformationrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
