# Generated by Django 5.1.6 on 2025-02-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("translation", "Translation"),
                            ("recommendation", "Recommendation"),
                            ("sentiment", "Sentiment Analysis"),
                        ],
                        help_text="Type of AI result.",
                        max_length=20,
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        help_text="The AI-generated result data in JSON format."
                    ),
                ),
                (
                    "source_model",
                    models.CharField(
                        help_text="Name of the source model (e.g., Lesson, Debate).",
                        max_length=100,
                    ),
                ),
                (
                    "source_object_id",
                    models.PositiveIntegerField(
                        help_text="ID of the source object for which the AI result was generated."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
