# Generated by Django 5.1.6 on 2025-02-11 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        help_text="JSON data representing skills and expertise.",
                        null=True,
                    ),
                ),
                (
                    "reputation_score",
                    models.FloatField(
                        default=0, help_text="Reputation score from the ekoh system."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User associated with this candidate profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExpertMatchRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the expertise required."
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        blank=True,
                        help_text="JSON detailing matching criteria.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the request was created.",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project needing expert matching.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_match_requests",
                        to="projects.project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="User who initiated the match request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expert_match_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MatchScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.FloatField(help_text="Computed compatibility score.")),
                (
                    "candidate",
                    models.ForeignKey(
                        help_text="Candidate profile being evaluated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_scores",
                        to="expert_match.candidateprofile",
                    ),
                ),
                (
                    "match_request",
                    models.ForeignKey(
                        help_text="The expert match request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_scores",
                        to="expert_match.expertmatchrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
