# Generated by Django 5.1.6 on 2025-02-11 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "biography",
                    models.TextField(
                        blank=True, help_text="Artist biography", null=True
                    ),
                ),
                (
                    "portfolio_url",
                    models.URLField(
                        blank=True, help_text="URL to the artist's portfolio", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, help_text="Additional artist metadata", null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated user for the artist profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the commission", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Details of the commission requirements"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Budget for the commission",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        help_text="Current status of the commission",
                        max_length=20,
                    ),
                ),
                (
                    "contract_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for the commission contract or payment agreement",
                        null=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Artist assigned to the commission",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions_assigned",
                        to="marketplace.artistprofile",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="User requesting the commission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MarketplaceListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(help_text="Title of the listing", max_length=255),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the listing"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for the artwork",
                        max_digits=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image for the listing",
                        upload_to="marketplace_listings/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("sold", "Sold"),
                            ("removed", "Removed"),
                        ],
                        default="active",
                        help_text="Listing status",
                        max_length=20,
                    ),
                ),
                (
                    "payment_details",
                    models.JSONField(
                        blank=True,
                        help_text="Payment details or integration data",
                        null=True,
                    ),
                ),
                (
                    "artist_profile",
                    models.ForeignKey(
                        help_text="Artist profile associated with this listing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_listings",
                        to="marketplace.artistprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
